# -*- coding: utf-8 -*-
"""Model_Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yfGXmrcs30VFHEzJfJkU4VtXuSnXeqGd
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense,BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

curl 'https://storage.googleapis.com/kaggle-data-sets/778086/1339204/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220218%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220218T142513Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=6e8298ec563e5118d4f3dba032c12d6346118c6e63e1ae4cae9cbe4f31cb68910fc004e05a24b153c2a89cf44ef40335f3ecf6261c2cb4488a762764e40d97c2465660488e5e8253aa27f5d7734cc34a463c52981f8ceadd6e6dfbd3b7751457a33b7ab1b25bfb1e858b94f02e7a6dfe3828045f8c1c9b42454a5ef71fce373563c53d8945884c6c18093b03501e6b10c6912faf0b5f7ece0704e0da9970c013f99166edfa9c66387bf090eeab1630434a98bab717a155728dffdcea1be862ae9b853c9e585127062c6d24836fb386db6a03e10f9bdf77c0b8664105e10dd2ceee9951f9b411a29a1b4ee80f242a2fc0842adc52aff8fbd1d2ff955ddbf5a0f0' \
  -H 'authority: storage.googleapis.com' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Mobile Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-ch-ua: "Opera";v="83", "Chromium";v="97", ";Not A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'referer: https://www.kaggle.com/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --compressed -o data.zip

unzip data.zip

main_dir = '/content/New Masks Dataset'
train_dir = os.path.join(main_dir,'Train')
test_dir = os.path.join(main_dir,'Test')
valid_dir = os.path.join(main_dir,'Validation')

train_mask_dir = os.path.join(train_dir,'Mask')
train_No_mask_dir = os.path.join(train_dir,'Non Mask')

train_mask_names = os.listdir(train_mask_dir)
print(train_mask_names[0:10])

train_No_mask_names = os.listdir(train_No_mask_dir)
print(train_No_mask_names[0:10])

mask_images = []

for i in train_mask_names:
  mask_images.append(os.path.join(train_mask_dir,i))

non_mask_images=[]

for i in train_No_mask_names:
  non_mask_images.append(os.path.join(train_No_mask_dir,i))

import plotly.express as px
from skimage import io
from skimage.transform import resize

fig,ax = plt.subplots(1,4,figsize=(15,5))
img1 = io.imread(mask_images[6])
img2 = io.imread(mask_images[9])
img3 = io.imread(mask_images[10])
img4 = io.imread(mask_images[18])

ax[0].imshow(img1)
ax[0].set_title("Mask_Image 6")

ax[1].imshow(img2)
ax[1].set_title("Mask_Image 9")

ax[2].imshow(img3)
ax[2].set_title("Mask_Image 10")

ax[3].imshow(img4)
ax[3].set_title("Mask_Image 18")


plt.show()

fig,ax = plt.subplots(1,4,figsize=(15,5))
img1 = io.imread(non_mask_images[0])
img2 = io.imread(non_mask_images[1])
img3 = io.imread(non_mask_images[2])
img4 = io.imread(non_mask_images[3])

ax[0].imshow(img1)
ax[0].set_title("Non_Mask_Image 1")

ax[1].imshow(img2)
ax[1].set_title("Non_Mask_Image 2")

ax[2].imshow(img3)
ax[2].set_title("Non_Mask_Image 3")

ax[3].imshow(img4)
ax[3].set_title("Non_Mask_Image 4")


plt.show()

train_datagen = ImageDataGenerator(rescale=1./255,
                                   zoom_range=0.2,
                                   rotation_range=25,
                                   horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)
valid_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir,
                                                    target_size=(300,300),
                                                    batch_size=32,
                                                    class_mode='binary')
test_generator = test_datagen.flow_from_directory(test_dir,
                                                  target_size=(300,300),
                                                  batch_size=32,
                                                  class_mode='binary')
valid_generator = valid_datagen.flow_from_directory(valid_dir,
                                                    target_size=(300,300),
                                                    batch_size=32,
                                                    class_mode='binary')

train_generator.class_indices

train_generator.image_shape

model = Sequential()

model.add(Conv2D(filters=32,kernel_size=(3,3),padding='same',input_shape=(300,300,3),activation='relu'))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.5))

model.add(Conv2D(filters=64,kernel_size=(3,3),padding='same',activation='relu'))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.5))

model.add(Conv2D(filters=32,kernel_size=(3,3),padding='same',activation='relu'))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.5))

model.add(Flatten())

model.add(Dense(256,activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.0001),metrics=['accuracy'])

model.summary()

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss',patience=4)

model_train = model.fit(train_generator,epochs=25,
          validation_data=valid_generator,
          batch_size=32)

import pandas as pd
metrics = pd.DataFrame(model.history.history)

metrics.head(10)

test_loss,test_accuracy = model.evaluate_generator(test_generator)

print('test_loss: ',test_loss)
print('test_accuracy: ',test_accuracy)

model.save('./roger.h5')

from google.colab import drive
drive.mount('/content/drive')

!cp roger.h5 ./drive/MyDrive/roger.h5

drive.flush_and_unmount()
print('All changes made in this colab session should now be visible in Drive.')


if __name__ == '__main__':
  app.run(main)
